### PR TITLE
Fix .wfn load_one() function

### PR DESCRIPTION
**Pull request by msricher**
I fixed the .wfn file load_one() function, so that it properly reads .wfn files according to the specification. This successfully loads the file that previously failed (commit ae7fa66).

### CODE REVIEW

**Comment by msricher** [comment]
@FarnazH

**Comment by msricher** [comment]
I will add the "dump_one" function for the .wfn format _to this pull request_ soon.

**Comment by msricher** [comment]
https://github.com/FarnazH/iodata/blob/374241edfefbdd1dee757cdff0de0bdbef5012d8/iodata/formats/wfn.py#L395

Here is the structure for writing the .wfn file. I'm just not sure about how to pull out all the variables from the IOData object, to write them.

**Comment by msricher** [comment]
I added the Fortran FORMAT specifiers from AIMPAC, as comments:
https://github.com/msricher/iodata/blob/86c4c2387026a545d9a0bf87ba3278cbde80a8f2/iodata/formats/wfn.py

**Comment by msricher** [comment]
@FarnazH  This is ready to merge if you like it. This pull request only contains the `load_one()` for *.WFN.

I have another branch on my fork, msricher/wfn_dump, which contains the `dump_one()` code. It's finished except for parsing the `obasis` to get centres, types, exponents.

**Comment by FarnazH** [comment]
@msricher Can you please look at `load_one()` of WFN to see how information is stored in `obasis` and use that to write information in `dump_one()`?

As I also wrote you, the fix of WFN load_one() looks good to me. Can you please add a test using the `cah110_hf_sto3g_g09.wfn` similar to other WFN tests? Then, please make a PR for this fix.

**Comment by msricher** [comment]
@FarnazH there is a test file in there for it.

I am going to work with Paul today (I think) to put in the dump_one() function.

**Pull request closed without merging**
